name: Deploy to Firebase

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: |
        npm install --legacy-peer-deps
        npm install --save-dev cross-env
    
    - name: Build
      run: npx cross-env CI=false npm run build
    
    - name: Deploy to Firebase (only on main branch)
      if: github.ref == 'refs/heads/main'
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: '${{ secrets.GITHUB_TOKEN }}'
        firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_WINDOWERP_3 }}'
        channelId: live
        projectId: ${{ secrets.FIREBASE_PROJECT_ID }}
    
    - name: Deploy to Firebase Preview (on PR)
      if: github.event_name == 'pull_request'
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: '${{ secrets.GITHUB_TOKEN }}'
        firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_WINDOWERP_3 }}'
        channelId: pr-${{ github.event.number }}
        projectId: ${{ secrets.FIREBASE_PROJECT_ID }} 